backend/controllers/BannerController.php
<?php

namespace backend\controllers;

use common\components\ReturnUrlCustom;
use common\models\Banner;
use common\models\BannerSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BannerController implements the CRUD actions for Banner model.
 */
class BannerController extends Controller
{
    public $enableCsrfValidation = false;

    public function actions()
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => '/img/banner/', // Directory URL address, where files are stored.
                'path' => '@frontend/web/img/banner' // Or absolute path to directory where files are stored.
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if (!\Yii::$app->user->isGuest) {
                                return \Yii::$app->user->id == 1;
                            } else {
                                return false;
                            }
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Banner models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BannerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Banner model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Banner model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Banner the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Banner::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new Banner model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Banner();

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $altUrl = ['index'];
            return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Banner model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $altUrl = ['index'];
            return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Banner model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        $altUrl = ['index'];
        return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
    }
}

backend/controllers/BlogCategoryController.php
<?php

namespace backend\controllers;

use common\components\ReturnUrlCustom;
use common\models\BlogCategory;
use common\models\BlogCategorySearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BlogCategoryController implements the CRUD actions for BlogCategory model.
 */
class BlogCategoryController extends Controller
{
    public $enableCsrfValidation = false;

    public function actions()
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => '/img/blog-category/', // Directory URL address, where files are stored.
                'path' => '@frontend/web/img/blog-category' // Or absolute path to directory where files are stored.
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if (!\Yii::$app->user->isGuest) {
                                return \Yii::$app->user->id == 1;
                            } else {
                                return false;
                            }
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BlogCategory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BlogCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BlogCategory model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the BlogCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BlogCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BlogCategory::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new BlogCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BlogCategory();

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $altUrl = ['index'];
            return $this->redirect(ReturnUrlCustom::getUrl($altUrl));

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing BlogCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $altUrl = ['index'];
            return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing BlogCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        $altUrl = ['index'];
        return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
    }
}

backend/controllers/BlogController.php
<?php

namespace backend\controllers;

use common\components\ReturnUrlCustom;
use common\models\Blog;
use common\models\BlogSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BlogController implements the CRUD actions for Blog model.
 */
class BlogController extends Controller
{
    public $enableCsrfValidation = false;

    public function actions()
    {
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => '/img/blog/', // Directory URL address, where files are stored.
                'path' => '@frontend/web/img/blog' // Or absolute path to directory where files are stored.
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            if (!\Yii::$app->user->isGuest) {
                                return \Yii::$app->user->id == 1;
                            } else {
                                return false;
                            }
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Blog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BlogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Blog model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Blog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Blog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Blog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new Blog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Blog();

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $altUrl = ['index'];
            return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Blog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $altUrl = ['index'];
            return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Blog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        $altUrl = ['index'];
        return $this->redirect(ReturnUrlCustom::getUrl($altUrl));
    }
}

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);

$js =
    <<< 'JS'
/* To initialize BS3 tooltips set this below */
$('body').tooltip({
    selector: "[data-toggle='tooltip']"
});
// $(function () { 
//     $("[data-toggle='tooltip']").tooltip(); 
// });
/* To initialize BS3 popovers set this below */
//$(function () { 
//    $("[data-toggle='popover']").popover(); 
//});
JS;
// Register tooltip/popover initialization javascript
$this->registerJs($js);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Back to public zone',
        'brandUrl' => '/',
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        if (Yii::$app->user->id == 1) {
            $menuItems = [
//                [
//                    'label' => Yii::t('app', 'Locations'),
//                    'items' => [
//                        ['label' => Yii::t('app', 'Locations'), 'url' => ['/location/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Location reviews'), 'url' => ['/location-review/index']],
//                        ['label' => Yii::t('app', 'Deals'), 'url' => ['/deal/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Regions'), 'url' => ['/location-region/index']],
//                        ['label' => Yii::t('app', 'Menu item types'), 'url' => ['/menu-item-type/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Preorders'), 'url' => ['/preorder/index']],
//                    ]
//                ],
//                [
//                    'label' => Yii::t('app', 'Shop'),
//                    'items' => [
//                        ['label' => Yii::t('app', 'Shop items'), 'url' => ['/shop-item/index']],
//                        ['label' => Yii::t('app', 'Orders'), 'url' => ['/order/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Coupons'), 'url' => ['/coupon/index']],
//                        ['label' => Yii::t('app', 'Sales'), 'url' => ['/discount/index']],
//                        ['label' => Yii::t('app', 'Categories'), 'url' => ['/shop-item-category/index']],
//                        ['label' => Yii::t('app', 'Item reviews'), 'url' => ['/shop-item-review/index']],
//                        ['label' => Yii::t('app', 'Suppliers'), 'url' => ['/supplier/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Sales with suppliers'), 'url' => ['/report/sales-with-suppliers']],
//                    ]
//                ],
//                [
//                    'label' => Yii::t('app', 'Strains'),
//                    'items' => [
//                        ['label' => Yii::t('app', 'Strains'), 'url' => ['/strain/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Properties'), 'url' => ['/property/index']],
//                        ['label' => Yii::t('app', 'Strain reviews'), 'url' => ['/strain-review/index']],
//                    ]
//                ],
//                [
//                    'label' => Yii::t('app', 'Medical ID'),
//                    'items' => [
//                        ['label' => Yii::t('app', 'Doctors'), 'url' => ['/doctor/index']],
//                        ['label' => Yii::t('app', 'Medical states'), 'url' => ['/medical-state/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Medical state FAQ'), 'url' => ['/medical-faq/index']],
//                    ]
//                ],
//                [
//                    'label' => Yii::t('app', 'Events'),
//                    'items' => [
//                        ['label' => Yii::t('app', 'Events'), 'url' => ['/event/index']],
//                        '<li class="divider"></li>',
//                        ['label' => Yii::t('app', 'Event states'), 'url' => ['/event-state/index']],
//                    ]
//                ],
                [
                    'label' => Yii::t('app', 'Blogs'),
                    'items' => [
                        ['label' => Yii::t('app', 'Blog posts'), 'url' => ['/blog/index']],
                        ['label' => Yii::t('app', 'Blog categories'), 'url' => ['/blog-category/index']],
                    ]
                ],
//                [
//                    'label' => Yii::t('app', 'SMS'),
//                    'items' => [
//                        ['label' => Yii::t('app', 'SMS messages'), 'url' => ['/sms-message/index']],
//                        ['label' => Yii::t('app', 'SMS usage'), 'url' => ['/report/sms-usage']],
//                    ]
//                ],
                ['label' => Yii::t('app', 'Banners'), 'url' => ['/banner/index']],
            ];
        }

        $menuItems[] = [
            'label' => Yii::t('app', 'Logout') . ' (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>